[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Form handling
# Temporarily disabled to debug form issues
# [forms]
#   honeypot = "bot-field"